# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186bf329b0d75ea4ea0609d5a71a652cf79f9ea2ece17d030df59c4e24edd57e90ca047a9c8b5011bf4e1aac5bc0f65bb49ad6e8c06a7c171dae9e670aaed247

test:
  secret_key_base: 85b95cfc064c572b449d1855e79068a8f355e4ef0d8ebde97ff8069f2a9ebd5a4d710f9af017075e9ba8126ec8eb3f6b0bb5451e4415c403df1573d68214fab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
